name: Build and Push Distroless Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image (distroless)
        uses: docker/build-push-action@v5
        with:
          context: ./backend/nestjs-task-management
          push: true
          tags: vishnu1183/task-management-nestjs:latest

      - name: Clean up
        run: docker system prune -af
