name: Build and Push Distroless Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image (distroless)
        uses: docker/build-push-action@v5
        with:
          context: ./backend/nestjs-task-management
          push: true
          tags: vishnu1183/task-management-nestjs:latest

      - name: Clean up
        run: docker system prune -af

      - name: Send email notification
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.EMAIL_SERVER }}
          server_port: ${{ secrets.EMAIL_PORT }}
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ✅ Docker Image Build & Front-end Deployment Successful
          body: |
            Your Docker image was built and pushed successfully,
            and Front-end Deployment as well.
            Repo: ${{ github.repository }}
            Tag: latest
            Time: ${{ github.event.head_commit.timestamp }}
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_FROM }}
